# Generated by Django 3.1.7 on 2021-03-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='display_name',
            field=models.CharField(max_length=180),
        ),
    ]
